language: rust
sudo: required
os:
  - linux
  - osx
rust:
  - "1.36.0"
services:
  - docker
before_deploy: "./build-release trlogic ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  provider: releases
#  api_key:
#    secure: ""
  file_glob: true
  file: "trlogic-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    rust: stable
    tags: true
